### ISSUE TITLE
When loading a barcode created by "CODE-39" or "CODE-128", the error message "Missing encoding table" appears.

### ISSUE THREAD

**Issue by griffonlee** [Kingal1337/flipper-barcode-generator#1]
Using FW: https://github.com/DarkFlippers/unleashed-firmware
When loading a barcode created by "CODE-39" or "CODE-128", the error message "Missing encoding table" appears.
![image](https://user-images.githubusercontent.com/82207710/219534430-3b2a4cc9-00af-4f00-9b54-142381a2c141.png)

Both code39_encodings.txt and code128_encodings.txt copied into SD Card/app_data/barcode_data/
![image](https://user-images.githubusercontent.com/82207710/219533662-5456bd7c-085f-43d4-8b82-dd8eeb838b04.png)

**Comment by Kingal1337** [comment]
there was a typo in the readme file. The `app_data` folder should be named `apps_data`
