### ISSUE TITLE
How can I create long code-39

### ISSUE THREAD

**Issue by nagamine-git** [Kingal1337/flipper-barcode-generator#12]
Hi there.

I tried to create a QR code by code-39, but it was cut.
Do you know how I can do it?

<img width="848" alt="web_gen" src="https://github.com/user-attachments/assets/b9db0963-5ada-420a-bd7c-c29262cd86af">

![f_gen](https://github.com/user-attachments/assets/eeb3496d-07a9-4ea4-afbb-e53d115585c5)

**Comment by Kingal1337** [comment]
The flipper screen is too small to support that many characters. The maximum number of characters the flipper supports is 8, this includes the start and stop characters (*). With the barcode provided, you would need to remove the last 2 characters 3 and 4 in order for a reader to scan the barcode. `*Abc-12*`
