### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by RogueMaster** [Kingal1337/flipper-barcode-generator#2]
Could you fix the compile issue on this file?

https://github.com/Kingal1337/flipper-barcode-generator/blob/master/views/message_view.c#L59

For now, I removed the whole function and call to it, but it does cause this compile error on OFW compile:
applications/external/barcode_app/views/message_view.c: In function 'message_view_free_model':
applications/external/barcode_app/views/message_view.c:59:28: error: unused variable 'model' [-Werror=unused-variable]
   59 |         MessageViewModel * model,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   ^~~~~
applications/services/gui/view.h:233:9: note: in definition of macro 'with_view_model'
  233 |         type = view_get_model(view);              \
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ^~~~

**Comment by Kingal1337** [comment]
That function wasn't necessary, I removed it from my version as well. It seems to compile fine now.

Also compiles fine in OFW
