### ISSUE TITLE
Codabar support?

### ISSUE THREAD

**Issue by vielmetti** [Kingal1337/flipper-barcode-generator#3]
My library supports "Codabar" for its bar code library cards - would love to have a library card on my Flipper Zero.

(No idea if this is hard or easy.)

**Comment by Kingal1337** [comment]
I have added Codabar support in the latest release, but depending on how many numbers are on your library card, this may or may not work since the Flipper Zero's screen is so small it can only support up to a maximum of 8 characters.

**Comment by vielmetti** [comment]
Thanks!
