### ISSUE TITLE
Can't create Code-128c

### ISSUE THREAD

**Issue by kichro** [Kingal1337/flipper-barcode-generator#6]
Hey, 

I can't create Code-128c since it's not listed in menu. Seems to me like create_view.c is not updated to support it yet.

Cheers.

**Comment by Kingal1337** [comment]
Are you using the correct version? I built a fresh copy of the official firmware with the barcode generator and I also tried to add the release .fap to my flipper. I was able to create a Code-128C barcode using both methods.

**Comment by kichro** [comment]
Okay, I feel really dumb now. I've downloaded the latest release again to the same folder. Windows even asked me to overwrite it (barcode-1.3.zip). Uploaded it again to Flipper and it works now, so I'm a bit confused. Sorry for wasting your time. I've literally spent 4 hours debugging the code yesterday and couldn't find what was wrong...
