### ISSUE TITLE
Enhancement ➡️ QRcodes

### ISSUE THREAD

**Issue by fabulouscoding** [Kingal1337/flipper-barcode-generator#7]
Hi, 

App is working great, well done ! 👏

I saw that the guy named @bmatcuk made QRcode application on the repo down bellow if it's interesting you to add this function or discuss with the GUY.

Here's the work ↙️

https://github.com/bmatcuk/flipperzero-qrcode

Bye, greetings from France

**Comment by Kingal1337** [comment]
I will look into it, but as of now it is not a big priority for me since there already is a dedicated app for it.

**Comment by fabulouscoding** [comment]
Ok bye man ✌️
