### ISSUE TITLE
Wrong # of characters when loading saved barcode file

### ISSUE THREAD

**Issue by AlexNashZemlyak** [Kingal1337/flipper-barcode-generator#9]
<img width="473" alt="flipper error" src="https://github.com/Kingal1337/flipper-barcode-generator/assets/10594671/1ea49da1-9aec-4027-8fb9-6a007d8863cd">

Latest flipper firmware, app is up to date, I can successfully create barcode (no matter what Type) but when I trying to load it, I get this message ( "Wrong # of characters")
what am I doing wrong?

**Comment by Kingal1337** [comment]
which barcode type are you using and what did you put in the data field?
Some barcode types require a specific number of characters

**Comment by AlexNashZemlyak** [comment]
С128 and all I had coded on flipper was numbers, the app generated the file but unable to read it back

> which barcode type are you using and what did you put in the data field? Some barcode types require a specific number of characters

**Comment by AlexNashZemlyak** [comment]
actually i had tried different types but result is the same

**Comment by Kingal1337** [comment]
I just did a fresh install of the official flipper firmware and installed the barcode app via the flipper app store. I have no problems with any of the barcode types.
I also installed RogueMasters firmware and it works fine there.

**Which firmware are you on? Official? RogueMaster? Unleased? Xtreme? other?**
**How did you get the app? app store? manual install? third-party firmware?**
**Also if it is possible could you send me the barcode file from your SD card?**


**To get the file**
1) Plug in your SD card to your computer
2) go to `apps_data` folder
3) go to `barcodes` folder
4) open your barcode file
5) copy the contents and paste it here. (Note: you could also attach the barcode.txt)

**Comment by AlexNashZemlyak** [comment]
I just changed type of my unreadable file from Code 128C to Code 128 and it works ( but reader can't read the code from Flipper's screen anyway)

My firmware is Unleashed

I got the app via store 
[Per.txt](https://github.com/Kingal1337/flipper-barcode-generator/files/14193005/Per.txt) - this one is opens
[PerC.txt](https://github.com/Kingal1337/flipper-barcode-generator/files/14193007/PerC.txt) - this one is not

**Comment by Kingal1337** [comment]
I see what the problem is now, Code128C must have an even number of characters in order for it to work, that is why you got the error "Wrong # of Characters". I will change it so it gives more descriptive errors.

The reason why it cant be read with the reader is because the screen is way too small to show that many characters, the flipper can probably show about 8 maybe 9 characters (using code128) before the code gets too large and overflows off the screen. 
The code you sent me is 21 characters, way too many for the flipper to handle
